### ISSUE TITLE
请问如何解决力度的问题？

### ISSUE THREAD

**Issue by LAITENGHUI** [tkzt/ddt-sharp-shooter#1]
我对flash不是很了解，不知道能不能够直接从网页中实时检测按下空格后的力度值，然后在适时释放空格。我想到的笨办法是可以用tensorflow分别把100格力度的图各自识别一下，感觉从识别到作出反应的延迟应该在可控范围吧。不知道您有没有尝试过。

**Comment by tkzt** [comment]
尝试过，可行，有空优化。

**Comment by tkzt** [comment]
https://github.com/boring-plans/ELingWang/issues/3#issuecomment-1120114360
