### ISSUE TITLE
大佬您好，我尝试了所有版本，发现所有打包好的程序都无法运行，代码也无法工作。

### ISSUE THREAD

**Issue by saya010** [tkzt/ddt-sharp-shooter#4]
如下是我的问题：
1.0.1 ：打包好的主程序无法打开；代码在PyC中无法打开；我自己py2app打包好的app无法打开。
1.0.2 ：打包好的主程序无法打开；代码在PyC中可以打开不闪退（正确运行否未知）；我自己py2app打包好的app可以打开不闪退（正确运行否未知）。
打开后只有一个DSS的GUI界面，写着DSS is READAY。但是没有光标，也没有输入框（我无法确定此时DSS处于在什么模式，无法得知是否正常工作）。在此版本我试过直接ttf35，如果界面选择浏览器（弹弹堂，则会跟游戏中的案件冲突）
2.0.1 打包好的主程序无法打开；代码在PyC中无法打开（闪退）；我自己py2app打包好的app无法打开。（闪退）
2.0.2打包好的主程序无法打开；代码在PyC中无法打开（打开后只有最上面的顶栏，没有窗口，看不到DSS is ready，且30秒左右，python提示无响应）；我自己py2app打包好的app无法打开。（打开后只有最上面的顶栏，没有窗口，看不到DSS is ready，且30秒左右，python提示无响应）

最后祝福您生活愉快，事业学业有成。如果需要更多测试，可以给我发消息，我会第一时间回复。

**Comment by saya010** [comment]
随着时间的推移，同年的回忆，听着BGM声音响起，还是同样感慨万分。
愿无聊人不无聊，愿枯燥day不枯燥。

**Comment by tkzt** [comment]
在 MacOS 上：

- 需要安装 libjpeg，`brew install libjpeg`
- 需要安装 tcl-tk，`brew install tcl-tk`
- 需要分别赋予 app，`监听键盘`、`辅助功能`、`屏幕录制` 权限
