### ISSUE TITLE
支持Windows, 需要做的改动

### ISSUE THREAD

**Issue by Freedomisgood** [tkzt/ddt-sharp-shooter#5]
1. windows下运行不支持main.py中使用到的Emoji表情文本。需要全部删除
2. gui.py中wm_attributes中不支持`_tk.wm_attributes('-transparent', 1)` , 会报错： `_tkinter.TclError: unknown color name `。需要删除

**Comment by tkzt** [comment]
Fixed in [0e90ba46](https://github.com/boring-plans/ddt-sharp-shooter/commit/0e90ba46df3802818deee0907c8ddc9d4471c02b)
