### ISSUE TITLE
This python does not have a shared library or framework

### ISSUE THREAD

**Issue by anonymous-20000** [tkzt/ddt-sharp-shooter#7]
你好，我运行了这个程序只后他会出现This python does not have a shared library or framework您这边有解决的方法吗

**Comment by tkzt** [comment]
Windows 下可以尝试下 PyInstaller（我还没试过），欢迎 PR 👾

**Comment by anonymous-20000** [comment]
> Windows 下可以尝试下 PyInstaller（我还没试过），欢迎 PR 👾

谢谢！！
